name: Deploy to Firebase Functions
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install dependencies
      run: npm install

    - name: 'Create .env file'
      env:
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        THE_MOVIE_DB_KEY: ${{ secrets.THE_MOVIE_DB_KEY }}
      run: |
        echo MONGO_DB_URI=$MONGO_DB_URI >> .env
        echo SERVICE_ACCOUNT=$SERVICE_ACCOUNT >> .env
        echo THE_MOVIE_DB_KEY=$THE_MOVIE_DB_KEY >> .env

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: npm run deploy